version: '3'
services:

  docker:
    image: ghcr.io/consensus-shipyard/ipc-dx-docker:sha-f48b7bb

    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/data:/tmp/data

    command: ["cd fendermint && cargo make -e BASE_DIR=/tmp/data/.ipc/${SUBNET_ID} -e SUBNET_ID=${SUBNET_ID} --makefile ./infra/Makefile.toml testnode"]


