version: '3'
services:

  docker:
    image: sha256:e1d75a83ea92cbb6913ead178f38e9a70b0349e080195a8ea405c9712988f350
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/data:/tmp/data

    command: ["cd fendermint && cargo make -e BASE_DIR=/tmp/data/.ipc/r0 --makefile ./infra/Makefile.toml testnode"]


