version: '3'
services:

  ipc-testnode:
    profiles: ["testnode"]
    image: ghcr.io/consensus-shipyard/ipc-dx-docker:sha-b8b9abf
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/data:/tmp/data

    command: ["cd fendermint && cargo make -e BASE_DIR=/tmp/data/.ipc/${SUBNET_ID} -e SUBNET_ID=${SUBNET_ID} --makefile ./infra/Makefile.toml testnode"]

  ipc-testnet:
    profiles: ["testnet"]
    image: ghcr.io/consensus-shipyard/ipc-dx-docker:sha-b8b9abf
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/data:/tmp/data

    command: ["cd fendermint && cargo make -e BASE_DIR=/tmp/data/.ipc/${SUBNET_ID} -e SUBNET_ID=${SUBNET_ID} --makefile ./infra/Makefile.toml testnet"]

  ipc:
    image: ghcr.io/consensus-shipyard/ipc-dx-docker:sha-b8b9abf
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/data:/tmp/data

    entrypoint: ["/bin/sh",  "-c", "cd fendermint && cargo make -e BASE_DIR=/tmp/data/.ipc/${SUBNET_ID} -e SUBNET_ID=${SUBNET_ID} --makefile ./infra/Makefile.toml"]

  ipc-cli:
    image: ghcr.io/consensus-shipyard/ipc-cli-docker:sha-713836e
    network_mode: host
    volumes:
      - ~:/root
