version: '3'
services:

  fendermint:
    image: sha256:9b95af07901f768fe829b041e21997a68699f637b8a755d39fc2141d11b242a2
#    image: ghcr.io/consensus-shipyard/ipc-dx-docker:sha-b8b9abf
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/data:/tmp/data
      - ~/.ipc:/root/.ipc

    entrypoint: /tmp/data/entrypoint.sh

  ipc-cli:
    image: ghcr.io/consensus-shipyard/ipc-cli-docker:sha-713836e
    network_mode: host
    volumes:
      - ~:/root
