version: '3'
services:

  ipc-testnode:
    profiles: ["testnode"]
    image: ghcr.io/hammertoe/ipc-dx-docker:sha-ec6b927
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/data:/tmp/data

    command: ["cd fendermint && cargo make -e BASE_DIR=/tmp/data/.ipc/${SUBNET_ID} -e SUBNET_ID=${SUBNET_ID} --makefile ./infra/Makefile.toml testnode"]

  ipc-testnet:
    profiles: ["testnet"]
    image: ghcr.io/hammertoe/ipc-dx-docker:sha-ec6b927
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/data:/tmp/data

    command: ["cd fendermint && cargo make -e BASE_DIR=/tmp/data/.ipc/${SUBNET_ID} -e SUBNET_ID=${SUBNET_ID} --makefile ./infra/Makefile.toml testnet"]

  ipc:
    image: ghcr.io/hammertoe/ipc-dx-docker:sha-ec6b927
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/data:/tmp/data

    entrypoint: ["/bin/sh",  "-c", "cd fendermint && cargo make -e BASE_DIR=/tmp/data/.ipc/${SUBNET_ID} -e SUBNET_ID=${SUBNET_ID} --makefile ./infra/Makefile.toml"]

  ipc-cli:
    image: sha256:a19748871608b84e7fb6f4898476719761d879b0f1acd27258805c6471bba242
    network_mode: host
    volumes:
      - ~:/root